name: exec

on:
  workflow_dispatch:
    inputs:
      notify_to_slack:
        description: "notify to slack"
        required: true
        default: "false"
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.6"

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Execute report.rb
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          HOGE_VALUE: ${{ vars.HOGE_VALUE }}
          RUN_FROM: from-github-actions
        run: |
          bundle exec ruby report.rb

      - name: Notify to Slack
        env:
          NOTIFY_TO_SLACK: ${{ github.event.inputs.notify_to_slack }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          [ "$NOTIFY_TO_SLACK" = "true" ] && curl -X POST -H 'Content-type: application/json' -d @slack_message.json $SLACK_WEBHOOK_URL || echo "skip notify to slack"
